const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
function load(name){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../src',name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:()=>({}),console});return exports;}
const imagery=load('imageryModel'),model=load('libraryModel');
const a={id:'a',place_id:'venue',save_id:'save',content_type:'place',image_choice:'cover'},b={...a,id:'b'},cover={key:'cover',source:'cover',uri:'cover'},google={key:'google:0',source:'google',uri:'google'};
const result={place_id:'venue',save_id:'save',gallery:[google,cover],selected:google,choices:[google,cover]};
test('stale single-venue cover disappears as soon as a sibling arrives offline',()=>{assert.equal(imagery.chosenImage(result,a,[a],'library').key,'cover');assert.equal(imagery.chosenImage(result,a,[a,b],'library').key,'google:0');assert.equal(imagery.allowedImages(result,{...a,save_entry_count:2},[a],'library').length,1);});
test('Google photos cannot appear alongside the Apple map',()=>{assert.equal(imagery.chosenImage(result,a,[a],'map').key,'cover');assert.equal(imagery.chosenImage(result,a,[a,b],'map'),null);});
test('photo choices cycle deterministically and owner choice wins refresh',()=>{assert.equal(imagery.nextImageChoice(result,'google:0'),'cover');assert.equal(imagery.nextImageChoice(result,'cover'),'google:0');assert.equal(imagery.chosenImage(result,a,[a],'library').key,'cover');});
test('offline operation persists a choice without altering note or ownership',()=>{const state=model.emptyLibrary();state.items=[{...a,note:'Dish I want',user_id:'owner'}];model.applyOperation(state,{id:'op',kind:'entry_edit',target:'a',body:{image_choice:'google:0'}});const next=state;assert.equal(next.items[0].image_choice,'google:0');assert.equal(next.items[0].note,'Dish I want');assert.equal(next.items[0].user_id,'owner');});

test('re-resolution never displays a previous venue image under a new place',()=>{assert.equal(imagery.chosenImage(result,{...a,place_id:'different'},[a],'library'),null);});

test('cross-batch duplicate photographs are hidden for unrelated places but shared venues are allowed',()=>{const other={...a,id:'other',place_id:'other-place',save_id:'other-save'};const r={...result,place_id:other.place_id,save_id:other.save_id};let merged=imagery.mergeImageryRecords({'library:a':result},{'library:other':r},[a,other]);assert.equal(merged['library:other'].gallery.length,0);other.place_id=a.place_id;r.place_id=a.place_id;merged=imagery.mergeImageryRecords({'library:a':result},{'library:other':r},[a,other]);assert.equal(merged['library:other'].gallery.length,2);});
