const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript'),yaml=require('js-yaml');
function load(name,mocks={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../src',name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:id=>mocks[id]||{},console});return exports;}
const venue=load('venueModel'),map=load('mapModel'),model=load('libraryModel'),org=load('organizationModel',{'./libraryModel':model,'./venueModel':venue});
const {venue_kinds:kinds,...registry}=yaml.load(fs.readFileSync(path.join(__dirname,'../../config/content_types.yaml'),'utf8'));
const entry=(id,kind='bar',city='Los Angeles',lat=34,lng=-118)=>({id,content_type:'place',venue_kind:kind,title:id,name:id,city,attributes:{venue_kind:kind},folders:[{id:'places'},{id:'la'}],created_at:'2026-09-08',place_id:id,lat,lng});
test('native bundled content types exclude resolver-only registry sections',()=>{
  const exports={};
  vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../app.config.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require,process:{env:{}},__dirname:path.join(__dirname,'..')});
  const types=exports.default.extra.contentTypes;
  for(const key of ['venue_kinds','venue_kind_signals','category_compatibility','venue_type_specificity']) assert.equal(types[key],undefined);
  assert.equal(Object.keys(types).length,10);
});
test('map excludes geo-never even when linked; nonempty chips share a deduplicated snapshot',()=>{const rows=[entry('bar'),entry('bar'),{...entry('recipe'),content_type:'recipe'},{...entry('workout'),content_type:'workout'},{...entry('unresolved'),place_id:null}];const snapshot=venue.venueSnapshot(rows,registry);assert.equal(snapshot.map.length,1);assert.equal(venue.countBy(snapshot.map,venue.entryKind).bar,1);});
test('50 mixed places cluster without overlapping centroids and majority is strict',()=>{const rows=Array.from({length:50},(_,i)=>entry(String(i),Object.keys(kinds)[i%16],'Los Angeles',34+(i%8)*.001,-118+(i%6)*.001));const region=map.bounds(rows);const clusters=map.collisionClusters(rows,region,390,640);assert.equal(clusters.reduce((n,c)=>n+c.members.length,0),50);assert.ok(clusters.some(c=>c.members.length>1));for(let i=0;i<clusters.length;i++)for(let j=i+1;j<clusters.length;j++){const a=clusters[i].coordinate,b=clusters[j].coordinate;assert.ok(Math.hypot((a.longitude-b.longitude)/region.longitudeDelta*390,(a.latitude-b.latitude)/region.latitudeDelta*640)>=52);}assert.equal(venue.majorityKind([entry('a'),entry('b'),entry('c','cafe')]),'bar');assert.equal(venue.majorityKind([entry('a'),entry('b','cafe')]),null);});
test('regional units and manual override do not depend on language',()=>{assert.equal(venue.formatDistance(1.609344,venue.distanceSystem('US')),'1.0 mi');assert.equal(venue.distanceSystem('GB'),'imperial');assert.equal(venue.distanceSystem('FR'),'metric');assert.equal(venue.distanceSystem('US','metric'),'metric');assert.equal(venue.distanceSystem('FR','imperial'),'imperial');});
test('both folder axes reach same private entry without creating database memberships',()=>{const rows=[entry('a'),entry('b','cafe'),entry('c','bar','San Francisco')];rows[2].folders=[{id:'places'},{id:'sf'}];const roots=[{id:'places',kind:'auto_type',content_type:'place'},{id:'la',kind:'auto_facet',content_type:'place',facet_key:'city'}];const folders=[...roots,...venue.typeFolders(rows,kinds,roots[0])];const before=JSON.stringify(rows);const byCity=org.libraryProjection(rows,folders,registry,{folderId:'la',venueKind:'bar'});const byKind=org.libraryProjection(rows,folders,registry,{folderId:'venue:bar',facet:'Los Angeles'});assert.equal(byCity.items[0].id,'a');assert.equal(byKind.items[0].id,'a');assert.equal(byCity.items.length,byKind.items.length);assert.equal(JSON.stringify(rows),before);assert.equal(folders.filter(f=>f.id.startsWith('venue:')).length,2);});
test('configuration-only seventeenth kind flows through dynamic projection and renderer contract',()=>{const extended={...kinds,observatory:{label:'Observatory',plural_label:'Observatories',icon:'telescope',color:'#315A89',google_types:['observatory']}};const rows=[entry('scope','observatory')];assert.equal(venue.typeFolders(rows,extended)[0].name,'Observatories');assert.equal(venue.countBy(venue.venueSnapshot(rows,registry).map,venue.entryKind).observatory,1);const icon=fs.readFileSync(path.join(__dirname,'../src/VenueKindIcon.tsx'),'utf8');assert.ok(icon.includes('kinds[kind]'));assert.ok(icon.includes('MaterialCommunityIcons.glyphMap'));});
test('search labels, map chips and derived folders count the same anchored bars',()=>{const rows=[entry('a'),entry('b'),entry('c','cafe')];const mapCount=venue.countBy(venue.venueSnapshot(rows,registry).map,venue.entryKind).bar;const folders=venue.typeFolders(rows,kinds);const view=org.libraryProjection(rows,folders,registry,{folderId:'venue:bar'});assert.equal(view.items.length,mapCount);assert.equal(model.searchLocal(rows,'Bars',kinds).length,mapCount);});
